# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
VERSION = 1.2.3
TARGET = LibrarianBooksCatalogue
DESTDIR = ../Release
QT += core gui sql
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT QT_DLL QT_SQL_LIB
INCLUDEPATH += ./GeneratedFiles \
    ./GeneratedFiles/Release \
    .
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
TRANSLATIONS += ./librarianbookscatalogue_en.ts \
    ./librarianbookscatalogue_pl.ts
win32:RC_FILE = LibrarianBooksCatalogue.rc
HEADERS += ./About.h \
    ./Drukuj.h \
    ./lbookscatalogue.h \
    ./resource.h \
    ./sqlite3.h \
    ./stdafx.h \
    ./Wyszukaj.h
SOURCES += ./About.cpp \
    ./Drukuj.cpp \
    ./lbookscatalogue.cpp \
    ./main.cpp \
    ./stdafx.cpp \
    ./Wyszukaj.cpp
FORMS += ./About.ui \
    ./Drukuj.ui \
    ./lbookscatalogue.ui \
    ./Wyszukaj.ui
TRANSLATIONS += ./librarianbookscatalogue_en.ts \
    ./librarianbookscatalogue_pl.ts
